version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - notes-network

  app:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: NotesDb
      DB_USER: sa
      DB_PASS: "YourStrong!Passw0rd"
    depends_on:
      - db
    networks:
      - notes-network

volumes:
  db-data:


networks:
  notes-network:
